#!/bin/bash

function __info () {
  # Author of changes: trimstray (contact@nslab.at)
  printf "  [ \033[00;34m..\033[0m ] %s\n" "$1"
}

function __success () {
  # Author of changes: trimstray (contact@nslab.at)
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" "$1"
}

function __user () {
  # Author of changes: trimstray (contact@nslab.at)
  printf "\r  [ \033[0;33m?\033[0m ] %s\n" "$1"
}

function __fail () {
  # Author of changes: trimstray (contact@nslab.at)
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] %s\n" "$1"
  echo ''
  exit 1
}

function __ensure_rsync() {
  if ! command -v rsync > /dev/null; then
    __fail "Please install rsync first"
    exit 1
  fi
}

function __load_config() {
  # Author of changes: trimstray (contact@nslab.at)
  [ ! -f "./$1" ] && __fail "No $1 file found"

  # seems to fail with process substitution in bash, e.g.:
  #     source <($WELDER_ROOT/libexec/priv/parse-config $1)
  # Author of changes: trimstray (contact@nslab.at)
  source /dev/stdin <<< "$(cat <("${WELDER_ROOT}/libexec/priv/parse-config" "./$1"))"

  if [ -z "${cfg_ssh_url-}" ];  then __fail "ssh_url variable must be set in $playbook.yml"; fi
  if [ -z "${cfg_ssh_port-}" ]; then cfg_ssh_port="22"; fi
}
