#!/usr/bin/env ruby
#
# Parses yaml config and returns values as a bash-compatible variables
#
require 'yaml'

file = ARGV.first
if file.nil? || !File.exist?(file)
  STDERR.puts "Pass a valid yaml file path"
  abort
end

config = YAML::load_file(file).map do |k, v|
  v = v.is_a?(Array) ? "(#{v.join(' ')})" : "'#{v}'"
  "cfg_#{k}=#{v}"
end

puts config.join("\n")
