#!/usr/bin/env bash

# Author of changes: trimstray (contact@nslab.at)

_cfg_ssh_url="$1"
_cfg_ssh_port="$2"
_script="$3"
_sudo_pass="$4"

ssh -t "$_cfg_ssh_url" -p "$_cfg_ssh_port" "echo "\$_sudo_pass" | sudo -S bash $_script"
_kstate="$?"

if [[ "$_kstate" -eq 0 ]] ; then

  true
  # printf "\n%s:\n  [\e[0;32m%s\e[m]\n" "Remote script state" "done"

else

  false
  # printf "\n%s:\n  [\e[0;31m%s\e[m]\n" "Remote script state" "fail"

fi

unset _sudo_pass
