#!/usr/bin/expect -f
#
# This script wraps the `ssh` command in an `expect` script,
# to automatically enter sudo passwords for the user.
#
set url [lindex $argv 0];
set ssh_port [lindex $argv 1];
set command [lindex $argv 2];
set sudo_pass [lindex $argv 3];

set timeout -1

spawn -noecho ssh -t $url -p $ssh_port $command
expect -exact "\[sudo\] password for "
send -- "$sudo_pass\r"
interact

lassign [wait] pid spawnid os_error_flag value

if {$os_error_flag == 0} {
  puts "exit status: $value"
} else {
  puts "errno: $value"
}
exit $value
