#!/bin/bash
#
# welder-run-script
#

[ -n "$DEBUG" ] && set -v

set -eu

playbook=$1
script=$2

[ -z "$playbook" ] && __fail "Usage: x run-script <playbook-name>"
# Author of changes: trimstray (contact@nslab.at)
[ ! -f "./${playbook}.yml" ] && __fail "No $playbook.yml file found"

__load_config "$playbook.yml"

ssh -t "$cfg_ssh_url" -p "$cfg_ssh_port" "$(< $script)"

__success "done!"
