#!/bin/bash
#
# Removes compiled files from the server
#

[ -n "$DEBUG" ] && set -v

set -eu

source $WELDER_ROOT/libexec/priv/_helpers

playbook=$1
[ -z "$playbook" ] && __fail "Usage: x cleanup <playbook-name>"

__load_config "$playbook.yml"

ssh -t $cfg_ssh_url "rm -r setup/"

__success "setup/ directory removed from $cfg_ssh_url"
