#!/bin/bash
#
# Removes compiled files from the server
#

[ -n "$DEBUG" ] && set -v

set -eu

source $WELDER_ROOT/libexec/priv/_helpers

__load_config "$@" || __fail "Usage: welder cleanup <playbook>"

ssh $cfg_ssh_url -p $cfg_ssh_port "rm -r setup/"

__success "setup/ directory removed from $cfg_ssh_url"
