#!/bin/bash

abort() {
  {
    if [ "$#" -eq 0 ]; then
      cat -
    else
      echo "welder: $*"
    fi
  } >&2
  exit 1
}

abs_dirname() {
  local path="$(realpath "$1")"
  echo "${path%/*}"
}

WELDER_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
WELDER_ROOT="$(abs_dirname $WELDER_ROOT)"
export WELDER_ROOT

source $WELDER_ROOT/libexec/priv/_helpers

bin_path="$(abs_dirname $0)"
export PATH="${bin_path}:${PATH}"

command=$1
case $command in
"" | "-h" | "--help")
    {
      welder-version
      welder-help
    } | abort
    ;;
-v | --version )
    exec welder-version
    ;;
*)
    command_path="$(command -v "welder-$command" || true)"
    [ -n "$command_path" ] || abort "no such command \`$command'"

    shift 1
    if [ "$1" = --help ]; then
      exec welder-help "$command"
    else
      exec "$command_path" "$@"
    fi
    ;;
esac
