#!/bin/bash

abort() {
  {
    if [ "$#" -eq 0 ]; then
      cat -
    else
      echo "welder: $*"
    fi
  } >&2
  exit 1
}

export WELDER_ROOT="$( cd "$( dirname "$( readlink ${BASH_SOURCE[0]} )" )/.." && pwd )"

export WELDER_CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/${0##*/}"
mkdir -p "$WELDER_CACHE"

source "$WELDER_ROOT/libexec/priv/_helpers"

if [[ $# -gt 0 ]]; then
  command="$1"
else
  command="help"
fi
case $command in
-h | --help)
    {
      welder version
      welder help
    } | abort
    ;;
-v | --version )
    exec welder version
    ;;
*)
    command_path="$WELDER_ROOT/libexec/welder-$command"
    [ -f "$command_path" ] || abort "no such command \`$command'"

    shift 1
    if [[ $# -gt 0 && $1 == "--help" ]]; then
      exec welder help "$command"
    else
      exec "$command_path" "$@"
    fi
    ;;
esac
