#!/bin/bash
#
# Removes compiled files from the server
#

# Author of changes: trimstray (contact@nslab.at)
# Declare first before used it.
cfg_ssh_url=""
cfg_ssh_port=""

[ -n "$DEBUG" ] && set -v

set -eu

# Author of changes: trimstray (contact@nslab.at)
# We are not able to determine the value of the WELDER_ROOT variable so:
# shellcheck disable=SC1090
source "${WELDER_ROOT}/libexec/priv/_helpers"

playbook=$1
[ -z "$playbook" ] && __fail "Usage: x cleanup <playbook-name>"

__load_config "$playbook.yml"

# Author of changes: trimstray (contact@nslab.at)
ssh "$cfg_ssh_url" -p "$cfg_ssh_port" "rm -r setup/"

__success "setup/ directory removed from $cfg_ssh_url"
